INSERT INTO `store` (`store_id`, `store_name`) VALUES
	(6, 'ENJOY VIDEO STORE'),
	(4, 'MATRIX VIDEO RENTAL'),
	(1, 'MAX VIDEO STORE'),
	(3, 'QUASIMODO E FIGLI VIDEO STORE'),
	(7, 'STORE VUOTO'),
	(5, 'SUPER 8 VIDEO RENTAL'),
	(2, 'UNIVERSAL VIDEO STORE');